CREATE TABLE IF NOT EXISTS common_code (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    group_code VARCHAR(50) NOT NULL,
    code VARCHAR(100) NOT NULL,
    key_value VARCHAR(150) NOT NULL,
    name_ko VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    attr1 VARCHAR(100) NULL,
    attr2 VARCHAR(100) NULL,
    attr3 VARCHAR(100) NULL,
    sort_order INT NOT NULL,
    use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_common_code_group_code_code (group_code, code)
);

INSERT INTO common_code (group_code, code, key_value, name_ko, name_en, attr1, attr2, attr3, sort_order) VALUES
('SINSUNG', 'BIGYEON', 'sinsung.bigyeon', '비견', 'Companion', NULL, NULL, NULL, 1),
('SINSUNG', 'GEOPJAE', 'sinsung.geopjae', '겁재', 'Rob Wealth', NULL, NULL, NULL, 2),
('SINSUNG', 'SIKSIN', 'sinsung.siksin', '식신', 'Eating God', NULL, NULL, NULL, 3),
('SINSUNG', 'SANGGWAN', 'sinsung.sanggwan', '상관', 'Hurting Officer', NULL, NULL, NULL, 4),
('SINSUNG', 'PYEONJAE', 'sinsung.pyeonjae', '편재', 'Indirect Wealth', NULL, NULL, NULL, 5),
('SINSUNG', 'JEONGJAE', 'sinsung.jeongjae', '정재', 'Direct Wealth', NULL, NULL, NULL, 6),
('SINSUNG', 'PYEONGWAN', 'sinsung.pyeongwan', '편관', 'Seven Killings', NULL, NULL, NULL, 7),
('SINSUNG', 'JEONGGWAN', 'sinsung.jeonggwan', '정관', 'Direct Officer', NULL, NULL, NULL, 8),
('SINSUNG', 'PYEONIN', 'sinsung.pyeonin', '편인', 'Indirect Resource', NULL, NULL, NULL, 9),
('SINSUNG', 'JEONGIN', 'sinsung.jeongin', '정인', 'Direct Resource', NULL, NULL, NULL, 10);

INSERT INTO common_code (group_code, code, key_value, name_ko, name_en, attr1, attr2, attr3, sort_order) VALUES
('ZODIAC', 'JA', 'zodiac.ja', '자', 'Rat', 'WATER', 'YANG', '子', 1),
('ZODIAC', 'CHUK', 'zodiac.chuk', '축', 'Ox', 'EARTH', 'YIN', '丑', 2),
('ZODIAC', 'IN', 'zodiac.in', '인', 'Tiger', 'WOOD', 'YANG', '寅', 3),
('ZODIAC', 'MYO', 'zodiac.myo', '묘', 'Rabbit', 'WOOD', 'YIN', '卯', 4),
('ZODIAC', 'JIN', 'zodiac.jin', '진', 'Dragon', 'EARTH', 'YANG', '辰', 5),
('ZODIAC', 'SA', 'zodiac.sa', '사', 'Snake', 'FIRE', 'YIN', '巳', 6),
('ZODIAC', 'O', 'zodiac.o', '오', 'Horse', 'FIRE', 'YANG', '午', 7),
('ZODIAC', 'MI', 'zodiac.mi', '미', 'Goat', 'EARTH', 'YIN', '未', 8),
('ZODIAC', 'SIN', 'zodiac.sin', '신', 'Monkey', 'METAL', 'YANG', '申', 9),
('ZODIAC', 'YU', 'zodiac.yu', '유', 'Rooster', 'METAL', 'YIN', '酉', 10),
('ZODIAC', 'SUL', 'zodiac.sul', '술', 'Dog', 'EARTH', 'YANG', '戌', 11),
('ZODIAC', 'HAE', 'zodiac.hae', '해', 'Pig', 'WATER', 'YIN', '亥', 12);

INSERT INTO common_code (group_code, code, key_value, name_ko, name_en, attr1, attr2, attr3, sort_order) VALUES
('SAJU_GANJI', 'GAPJA', 'ganji.gapja', '갑자', 'Gapja', '甲子', 'GAP', 'JA', 1),
('SAJU_GANJI', 'EULCHUK', 'ganji.eulchuk', '을축', 'Eulchuk', '乙丑', 'EUL', 'CHUK', 2),
('SAJU_GANJI', 'BYEONGIN', 'ganji.byeongin', '병인', 'Byeongin', '丙寅', 'BYEONG', 'IN', 3),
('SAJU_GANJI', 'JEONGMYO', 'ganji.jeongmyo', '정묘', 'Jeongmyo', '丁卯', 'JEONG', 'MYO', 4),
('SAJU_GANJI', 'MUJIN', 'ganji.mujin', '무진', 'Mujin', '戊辰', 'MU', 'JIN', 5),
('SAJU_GANJI', 'GISA', 'ganji.gisa', '기사', 'Gisa', '己巳', 'GI', 'SA', 6),
('SAJU_GANJI', 'GYEONGO', 'ganji.gyeongo', '경오', 'Gyeongo', '庚午', 'GYEONG', 'O', 7),
('SAJU_GANJI', 'SINMI', 'ganji.sinmi', '신미', 'Sinmi', '辛未', 'SIN', 'MI', 8),
('SAJU_GANJI', 'IMSIN', 'ganji.imsin', '임신', 'Imsin', '壬申', 'IM', 'SIN', 9),
('SAJU_GANJI', 'GYEYU', 'ganji.gyeyu', '계유', 'Gyeyu', '癸酉', 'GYE', 'YU', 10),
('SAJU_GANJI', 'GAPSUL', 'ganji.gapsul', '갑술', 'Gapsul', '甲戌', 'GAP', 'SUL', 11),
('SAJU_GANJI', 'EULHAE', 'ganji.eulhae', '을해', 'Eulhae', '乙亥', 'EUL', 'HAE', 12),
('SAJU_GANJI', 'BYEONGJA', 'ganji.byeongja', '병자', 'Byeongja', '丙子', 'BYEONG', 'JA', 13),
('SAJU_GANJI', 'JEONGCHUK', 'ganji.jeongchuk', '정축', 'Jeongchuk', '丁丑', 'JEONG', 'CHUK', 14),
('SAJU_GANJI', 'MUIN', 'ganji.muin', '무인', 'Muin', '戊寅', 'MU', 'IN', 15),
('SAJU_GANJI', 'GIMYO', 'ganji.gimyo', '기묘', 'Gimyo', '己卯', 'GI', 'MYO', 16),
('SAJU_GANJI', 'GYEONGJIN', 'ganji.gyeongjin', '경진', 'Gyeongjin', '庚辰', 'GYEONG', 'JIN', 17),
('SAJU_GANJI', 'SINSA', 'ganji.sinsa', '신사', 'Sinsa', '辛巳', 'SIN', 'SA', 18),
('SAJU_GANJI', 'IMO', 'ganji.imo', '임오', 'Imo', '壬午', 'IM', 'O', 19),
('SAJU_GANJI', 'GYEMI', 'ganji.gyemi', '계미', 'Gyemi', '癸未', 'GYE', 'MI', 20),
('SAJU_GANJI', 'GAPSIN', 'ganji.gapsin', '갑신', 'Gapsin', '甲申', 'GAP', 'SIN', 21),
('SAJU_GANJI', 'EULYU', 'ganji.eulyu', '을유', 'Eulyu', '乙酉', 'EUL', 'YU', 22),
('SAJU_GANJI', 'BYEONGSUL', 'ganji.byeongsul', '병술', 'Byeongsul', '丙戌', 'BYEONG', 'SUL', 23),
('SAJU_GANJI', 'JEONGHAE', 'ganji.jeonghae', '정해', 'Jeonghae', '丁亥', 'JEONG', 'HAE', 24),
('SAJU_GANJI', 'MUJA', 'ganji.muja', '무자', 'Muja', '戊子', 'MU', 'JA', 25),
('SAJU_GANJI', 'GICHUK', 'ganji.gichuk', '기축', 'Gichuk', '己丑', 'GI', 'CHUK', 26),
('SAJU_GANJI', 'GYEONGIN', 'ganji.gyeongin', '경인', 'Gyeongin', '庚寅', 'GYEONG', 'IN', 27),
('SAJU_GANJI', 'SINMYO', 'ganji.sinmyo', '신묘', 'Sinmyo', '辛卯', 'SIN', 'MYO', 28),
('SAJU_GANJI', 'IMJIN', 'ganji.imjin', '임진', 'Imjin', '壬辰', 'IM', 'JIN', 29),
('SAJU_GANJI', 'GYESA', 'ganji.gyesa', '계사', 'Gyesa', '癸巳', 'GYE', 'SA', 30),
('SAJU_GANJI', 'GAPO', 'ganji.gapo', '갑오', 'Gapo', '甲午', 'GAP', 'O', 31),
('SAJU_GANJI', 'EULMI', 'ganji.eulmi', '을미', 'Eulmi', '乙未', 'EUL', 'MI', 32),
('SAJU_GANJI', 'BYEONGSIN', 'ganji.byeongsin', '병신', 'Byeongsin', '丙申', 'BYEONG', 'SIN', 33),
('SAJU_GANJI', 'JEONGYU', 'ganji.jeongyu', '정유', 'Jeongyu', '丁酉', 'JEONG', 'YU', 34),
('SAJU_GANJI', 'MUSUL', 'ganji.musul', '무술', 'Musul', '戊戌', 'MU', 'SUL', 35),
('SAJU_GANJI', 'GIHAE', 'ganji.gihae', '기해', 'Gihae', '己亥', 'GI', 'HAE', 36),
('SAJU_GANJI', 'GYEONGJA', 'ganji.gyeongja', '경자', 'Gyeongja', '庚子', 'GYEONG', 'JA', 37),
('SAJU_GANJI', 'SINCHUK', 'ganji.sinchuk', '신축', 'Sinchuk', '辛丑', 'SIN', 'CHUK', 38),
('SAJU_GANJI', 'IMIN', 'ganji.imin', '임인', 'Imin', '壬寅', 'IM', 'IN', 39),
('SAJU_GANJI', 'GYEMYO', 'ganji.gyemyo', '계묘', 'Gyemyo', '癸卯', 'GYE', 'MYO', 40),
('SAJU_GANJI', 'GAPJIN', 'ganji.gapjin', '갑진', 'Gapjin', '甲辰', 'GAP', 'JIN', 41),
('SAJU_GANJI', 'EULSA', 'ganji.eulsa', '을사', 'Eulsa', '乙巳', 'EUL', 'SA', 42),
('SAJU_GANJI', 'BYEONGO', 'ganji.byeongo', '병오', 'Byeongo', '丙午', 'BYEONG', 'O', 43),
('SAJU_GANJI', 'JEONGMI', 'ganji.jeongmi', '정미', 'Jeongmi', '丁未', 'JEONG', 'MI', 44),
('SAJU_GANJI', 'MUSIN', 'ganji.musin', '무신', 'Musin', '戊申', 'MU', 'SIN', 45),
('SAJU_GANJI', 'GIYU', 'ganji.giyu', '기유', 'Giyu', '己酉', 'GI', 'YU', 46),
('SAJU_GANJI', 'GYEONGSUL', 'ganji.gyeongsul', '경술', 'Gyeongsul', '庚戌', 'GYEONG', 'SUL', 47),
('SAJU_GANJI', 'SINHAE', 'ganji.sinhae', '신해', 'Sinhae', '辛亥', 'SIN', 'HAE', 48),
('SAJU_GANJI', 'IMJA', 'ganji.imja', '임자', 'Imja', '壬子', 'IM', 'JA', 49),
('SAJU_GANJI', 'GYECHUK', 'ganji.gyechuk', '계축', 'Gyechuk', '癸丑', 'GYE', 'CHUK', 50),
('SAJU_GANJI', 'GAPIN', 'ganji.gapin', '갑인', 'Gapin', '甲寅', 'GAP', 'IN', 51),
('SAJU_GANJI', 'EULMYO', 'ganji.eulmyo', '을묘', 'Eulmyo', '乙卯', 'EUL', 'MYO', 52),
('SAJU_GANJI', 'BYEONGJIN', 'ganji.byeongjin', '병진', 'Byeongjin', '丙辰', 'BYEONG', 'JIN', 53),
('SAJU_GANJI', 'JEONGSA', 'ganji.jeongsa', '정사', 'Jeongsa', '丁巳', 'JEONG', 'SA', 54),
('SAJU_GANJI', 'MUO', 'ganji.muo', '무오', 'Muo', '戊午', 'MU', 'O', 55),
('SAJU_GANJI', 'GIMI', 'ganji.gimi', '기미', 'Gimi', '己未', 'GI', 'MI', 56),
('SAJU_GANJI', 'GYEONGSIN', 'ganji.gyeongsin', '경신', 'Gyeongsin', '庚申', 'GYEONG', 'SIN', 57),
('SAJU_GANJI', 'SINYU', 'ganji.sinyu', '신유', 'Sinyu', '辛酉', 'SIN', 'YU', 58),
('SAJU_GANJI', 'IMSUL', 'ganji.imsul', '임술', 'Imsul', '壬戌', 'IM', 'SUL', 59),
('SAJU_GANJI', 'GYEHAE', 'ganji.gyehae', '계해', 'Gyehae', '癸亥', 'GYE', 'HAE', 60);

INSERT INTO common_code (group_code, code, key_value, name_ko, name_en, attr1, attr2, attr3, sort_order) VALUES
('TAROT_CARD', 'THE_FOOL', 'tarot.00', '바보', 'The Fool', 'MAJOR', NULL, '0', 1),
('TAROT_CARD', 'THE_MAGICIAN', 'tarot.01', '마법사', 'The Magician', 'MAJOR', NULL, '1', 2),
('TAROT_CARD', 'THE_HIGH_PRIESTESS', 'tarot.02', '여사제', 'The High Priestess', 'MAJOR', NULL, '2', 3),
('TAROT_CARD', 'THE_EMPRESS', 'tarot.03', '여황제', 'The Empress', 'MAJOR', NULL, '3', 4),
('TAROT_CARD', 'THE_EMPEROR', 'tarot.04', '황제', 'The Emperor', 'MAJOR', NULL, '4', 5),
('TAROT_CARD', 'THE_HIEROPHANT', 'tarot.05', '교황', 'The Hierophant', 'MAJOR', NULL, '5', 6),
('TAROT_CARD', 'THE_LOVERS', 'tarot.06', '연인', 'The Lovers', 'MAJOR', NULL, '6', 7),
('TAROT_CARD', 'THE_CHARIOT', 'tarot.07', '전차', 'The Chariot', 'MAJOR', NULL, '7', 8),
('TAROT_CARD', 'STRENGTH', 'tarot.08', '힘', 'Strength', 'MAJOR', NULL, '8', 9),
('TAROT_CARD', 'THE_HERMIT', 'tarot.09', '은둔자', 'The Hermit', 'MAJOR', NULL, '9', 10),
('TAROT_CARD', 'WHEEL_OF_FORTUNE', 'tarot.10', '운명의 수레바퀴', 'Wheel of Fortune', 'MAJOR', NULL, '10', 11),
('TAROT_CARD', 'JUSTICE', 'tarot.11', '정의', 'Justice', 'MAJOR', NULL, '11', 12),
('TAROT_CARD', 'THE_HANGED_MAN', 'tarot.12', '매달린 남자', 'The Hanged Man', 'MAJOR', NULL, '12', 13),
('TAROT_CARD', 'DEATH', 'tarot.13', '죽음', 'Death', 'MAJOR', NULL, '13', 14),
('TAROT_CARD', 'TEMPERANCE', 'tarot.14', '절제', 'Temperance', 'MAJOR', NULL, '14', 15),
('TAROT_CARD', 'THE_DEVIL', 'tarot.15', '악마', 'The Devil', 'MAJOR', NULL, '15', 16),
('TAROT_CARD', 'THE_TOWER', 'tarot.16', '탑', 'The Tower', 'MAJOR', NULL, '16', 17),
('TAROT_CARD', 'THE_STAR', 'tarot.17', '별', 'The Star', 'MAJOR', NULL, '17', 18),
('TAROT_CARD', 'THE_MOON', 'tarot.18', '달', 'The Moon', 'MAJOR', NULL, '18', 19),
('TAROT_CARD', 'THE_SUN', 'tarot.19', '태양', 'The Sun', 'MAJOR', NULL, '19', 20),
('TAROT_CARD', 'JUDGEMENT', 'tarot.20', '심판', 'Judgement', 'MAJOR', NULL, '20', 21),
('TAROT_CARD', 'THE_WORLD', 'tarot.21', '세계', 'The World', 'MAJOR', NULL, '21', 22),
('TAROT_CARD', 'ACE_OF_WANDS', 'tarot.22', '완드 에이스', 'Ace of Wands', 'MINOR', 'WANDS', '22', 23),
('TAROT_CARD', 'TWO_OF_WANDS', 'tarot.23', '완드 2', 'Two of Wands', 'MINOR', 'WANDS', '23', 24),
('TAROT_CARD', 'THREE_OF_WANDS', 'tarot.24', '완드 3', 'Three of Wands', 'MINOR', 'WANDS', '24', 25),
('TAROT_CARD', 'FOUR_OF_WANDS', 'tarot.25', '완드 4', 'Four of Wands', 'MINOR', 'WANDS', '25', 26),
('TAROT_CARD', 'FIVE_OF_WANDS', 'tarot.26', '완드 5', 'Five of Wands', 'MINOR', 'WANDS', '26', 27),
('TAROT_CARD', 'SIX_OF_WANDS', 'tarot.27', '완드 6', 'Six of Wands', 'MINOR', 'WANDS', '27', 28),
('TAROT_CARD', 'SEVEN_OF_WANDS', 'tarot.28', '완드 7', 'Seven of Wands', 'MINOR', 'WANDS', '28', 29),
('TAROT_CARD', 'EIGHT_OF_WANDS', 'tarot.29', '완드 8', 'Eight of Wands', 'MINOR', 'WANDS', '29', 30),
('TAROT_CARD', 'NINE_OF_WANDS', 'tarot.30', '완드 9', 'Nine of Wands', 'MINOR', 'WANDS', '30', 31),
('TAROT_CARD', 'TEN_OF_WANDS', 'tarot.31', '완드 10', 'Ten of Wands', 'MINOR', 'WANDS', '31', 32),
('TAROT_CARD', 'PAGE_OF_WANDS', 'tarot.32', '완드 페이지', 'Page of Wands', 'MINOR', 'WANDS', '32', 33),
('TAROT_CARD', 'KNIGHT_OF_WANDS', 'tarot.33', '완드 나이트', 'Knight of Wands', 'MINOR', 'WANDS', '33', 34),
('TAROT_CARD', 'QUEEN_OF_WANDS', 'tarot.34', '완드 퀸', 'Queen of Wands', 'MINOR', 'WANDS', '34', 35),
('TAROT_CARD', 'KING_OF_WANDS', 'tarot.35', '완드 킹', 'King of Wands', 'MINOR', 'WANDS', '35', 36),
('TAROT_CARD', 'ACE_OF_CUPS', 'tarot.36', '컵 에이스', 'Ace of Cups', 'MINOR', 'CUPS', '36', 37),
('TAROT_CARD', 'TWO_OF_CUPS', 'tarot.37', '컵 2', 'Two of Cups', 'MINOR', 'CUPS', '37', 38),
('TAROT_CARD', 'THREE_OF_CUPS', 'tarot.38', '컵 3', 'Three of Cups', 'MINOR', 'CUPS', '38', 39),
('TAROT_CARD', 'FOUR_OF_CUPS', 'tarot.39', '컵 4', 'Four of Cups', 'MINOR', 'CUPS', '39', 40),
('TAROT_CARD', 'FIVE_OF_CUPS', 'tarot.40', '컵 5', 'Five of Cups', 'MINOR', 'CUPS', '40', 41),
('TAROT_CARD', 'SIX_OF_CUPS', 'tarot.41', '컵 6', 'Six of Cups', 'MINOR', 'CUPS', '41', 42),
('TAROT_CARD', 'SEVEN_OF_CUPS', 'tarot.42', '컵 7', 'Seven of Cups', 'MINOR', 'CUPS', '42', 43),
('TAROT_CARD', 'EIGHT_OF_CUPS', 'tarot.43', '컵 8', 'Eight of Cups', 'MINOR', 'CUPS', '43', 44),
('TAROT_CARD', 'NINE_OF_CUPS', 'tarot.44', '컵 9', 'Nine of Cups', 'MINOR', 'CUPS', '44', 45),
('TAROT_CARD', 'TEN_OF_CUPS', 'tarot.45', '컵 10', 'Ten of Cups', 'MINOR', 'CUPS', '45', 46),
('TAROT_CARD', 'PAGE_OF_CUPS', 'tarot.46', '컵 페이지', 'Page of Cups', 'MINOR', 'CUPS', '46', 47),
('TAROT_CARD', 'KNIGHT_OF_CUPS', 'tarot.47', '컵 나이트', 'Knight of Cups', 'MINOR', 'CUPS', '47', 48),
('TAROT_CARD', 'QUEEN_OF_CUPS', 'tarot.48', '컵 퀸', 'Queen of Cups', 'MINOR', 'CUPS', '48', 49),
('TAROT_CARD', 'KING_OF_CUPS', 'tarot.49', '컵 킹', 'King of Cups', 'MINOR', 'CUPS', '49', 50),
('TAROT_CARD', 'ACE_OF_SWORDS', 'tarot.50', '소드 에이스', 'Ace of Swords', 'MINOR', 'SWORDS', '50', 51),
('TAROT_CARD', 'TWO_OF_SWORDS', 'tarot.51', '소드 2', 'Two of Swords', 'MINOR', 'SWORDS', '51', 52),
('TAROT_CARD', 'THREE_OF_SWORDS', 'tarot.52', '소드 3', 'Three of Swords', 'MINOR', 'SWORDS', '52', 53),
('TAROT_CARD', 'FOUR_OF_SWORDS', 'tarot.53', '소드 4', 'Four of Swords', 'MINOR', 'SWORDS', '53', 54),
('TAROT_CARD', 'FIVE_OF_SWORDS', 'tarot.54', '소드 5', 'Five of Swords', 'MINOR', 'SWORDS', '54', 55),
('TAROT_CARD', 'SIX_OF_SWORDS', 'tarot.55', '소드 6', 'Six of Swords', 'MINOR', 'SWORDS', '55', 56),
('TAROT_CARD', 'SEVEN_OF_SWORDS', 'tarot.56', '소드 7', 'Seven of Swords', 'MINOR', 'SWORDS', '56', 57),
('TAROT_CARD', 'EIGHT_OF_SWORDS', 'tarot.57', '소드 8', 'Eight of Swords', 'MINOR', 'SWORDS', '57', 58),
('TAROT_CARD', 'NINE_OF_SWORDS', 'tarot.58', '소드 9', 'Nine of Swords', 'MINOR', 'SWORDS', '58', 59),
('TAROT_CARD', 'TEN_OF_SWORDS', 'tarot.59', '소드 10', 'Ten of Swords', 'MINOR', 'SWORDS', '59', 60),
('TAROT_CARD', 'PAGE_OF_SWORDS', 'tarot.60', '소드 페이지', 'Page of Swords', 'MINOR', 'SWORDS', '60', 61),
('TAROT_CARD', 'KNIGHT_OF_SWORDS', 'tarot.61', '소드 나이트', 'Knight of Swords', 'MINOR', 'SWORDS', '61', 62),
('TAROT_CARD', 'QUEEN_OF_SWORDS', 'tarot.62', '소드 퀸', 'Queen of Swords', 'MINOR', 'SWORDS', '62', 63),
('TAROT_CARD', 'KING_OF_SWORDS', 'tarot.63', '소드 킹', 'King of Swords', 'MINOR', 'SWORDS', '63', 64),
('TAROT_CARD', 'ACE_OF_PENTACLES', 'tarot.64', '펜타클 에이스', 'Ace of Pentacles', 'MINOR', 'PENTACLES', '64', 65),
('TAROT_CARD', 'TWO_OF_PENTACLES', 'tarot.65', '펜타클 2', 'Two of Pentacles', 'MINOR', 'PENTACLES', '65', 66),
('TAROT_CARD', 'THREE_OF_PENTACLES', 'tarot.66', '펜타클 3', 'Three of Pentacles', 'MINOR', 'PENTACLES', '66', 67),
('TAROT_CARD', 'FOUR_OF_PENTACLES', 'tarot.67', '펜타클 4', 'Four of Pentacles', 'MINOR', 'PENTACLES', '67', 68),
('TAROT_CARD', 'FIVE_OF_PENTACLES', 'tarot.68', '펜타클 5', 'Five of Pentacles', 'MINOR', 'PENTACLES', '68', 69),
('TAROT_CARD', 'SIX_OF_PENTACLES', 'tarot.69', '펜타클 6', 'Six of Pentacles', 'MINOR', 'PENTACLES', '69', 70),
('TAROT_CARD', 'SEVEN_OF_PENTACLES', 'tarot.70', '펜타클 7', 'Seven of Pentacles', 'MINOR', 'PENTACLES', '70', 71),
('TAROT_CARD', 'EIGHT_OF_PENTACLES', 'tarot.71', '펜타클 8', 'Eight of Pentacles', 'MINOR', 'PENTACLES', '71', 72),
('TAROT_CARD', 'NINE_OF_PENTACLES', 'tarot.72', '펜타클 9', 'Nine of Pentacles', 'MINOR', 'PENTACLES', '72', 73),
('TAROT_CARD', 'TEN_OF_PENTACLES', 'tarot.73', '펜타클 10', 'Ten of Pentacles', 'MINOR', 'PENTACLES', '73', 74),
('TAROT_CARD', 'PAGE_OF_PENTACLES', 'tarot.74', '펜타클 페이지', 'Page of Pentacles', 'MINOR', 'PENTACLES', '74', 75),
('TAROT_CARD', 'KNIGHT_OF_PENTACLES', 'tarot.75', '펜타클 나이트', 'Knight of Pentacles', 'MINOR', 'PENTACLES', '75', 76),
('TAROT_CARD', 'QUEEN_OF_PENTACLES', 'tarot.76', '펜타클 퀸', 'Queen of Pentacles', 'MINOR', 'PENTACLES', '76', 77),
('TAROT_CARD', 'KING_OF_PENTACLES', 'tarot.77', '펜타클 킹', 'King of Pentacles', 'MINOR', 'PENTACLES', '77', 78);
